backend:
  name: git-gateway
  branch: main
media_folder: "uploads"
public_folder: "/uploads"
collections:
    - name: "meetings"
    label: "Meetings"
    folder: "content/meetings"
    create: true
    fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Date", name: "date", widget: "datetime"}
            - {label: "Document", name: "file", widget: "file"}